completely reworked, new README, new ./jroscore which handles CTRL+C, refactored packages, renamed project

diff --git a/jroscore b/jroscore
--- a/jroscore
+++ b/jroscore
@@ -1,65 +1,78 @@
 #!/bin/sh
-
-# This thing will start the java implementation of roscore 
-# The default ROS_MASTER_URI is set to: http://localhost:11311 , the same as for ROS 
-# You can specify the ROS_MASTER_URI by:
-#   - passing the URI as parameter
-#   - or ssetting variable $ROS_MASTER_URI (as is made by the ROS installation)
 #
+# Launches java implementation of ROS core. This script uses jars generated by the command ./gradlew installApp, 
+# but does not use build/install/jroscore/bin/jroscore script.
+# 
+# Jroscore is now able to handle SIGTERM signal: (CTRL+C) is passed from the command line to ShutDownInterceptor class, 
+# so the RosCore has time to free its address and exit clearly.
 #
+# author Jaroslav Vitku [vitkujar@fel.cvut.cz]
 
-# by Jaroslav Vitku
-
-
-# this is where I am (and all things to copy)
+DEFAULTURI="http://localhost:11311/"
 BASEDIR=$(dirname $0)
 
-
-# print usage
-pu()
+##################################################### Help
+usage()
 {
-	echo " "
-	echo "====================== Usage ====================x"
-	echo "Script 'jrsocore' launches the roscore with URI specified in $ROS_MASTER_URI variable"
-	echo "Which has currently this value: "$ROS_MASTER_URI
-	echo " "
-	echo "Or e.g. script 'run http://localhost:11311' starts the master with a valid URI" 
-	echo "================================================="
-	echo " "
+    echo " "
+    echo "Script launches the (java implementation of) RosCore with URI specified in the ROS_MASTER_URI variable"
+    echo "If not set, the default URI is used: $DEFAULTURI, usage:"
+    echo "-h|\?|help    this help"
+    echo "-u|uri        specify your custom URI\n"
 }
 
-HELP="help"
+##################################################### Parse command line
+BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # we are here
+URI=0
 
-# specify the name of the roscore project
-NAME=jroscore
+OPTIND=1        # Reset in case getopts has been used previously in the shell.
+while getopts "urih?help:" opt; do
+    case "$opt" in
+        h|\?|help)
+        usage
+        exit 0
+        ;;
+        u|uri)
+        URI=1
+        ;;
+    esac
+done
 
-# determine the absollute path to the java roscore isntallation 
-PTH=$BASEDIR"/build/install/jroscore/bin/"
-cd $PTH
+shift $((OPTIND-1))
+[ "$1" = "--" ] && shift
 
-#define defailt URI:
-DEFAULTURI="http://localhost:11311/"
-
-# if no argument specified, try to run based on the environment variable
-if [ "$#" -eq "0" ]; then
-    
-    # check whether ROS_MASTER_URI variable is set (if ROS is installed...)
-    if [ -z "$ROS_PACKAGE_PATH" ]; then
-        echo "ROS probably not installed and you did not specify your URI, so setting the default one."
-        ROS_MASTER_URI=$DEFAULTURI
-    fi
-	./$NAME $DEFAULTURI
-	
-elif [ "$#" -eq "1" ]; then
-	# want some help?
-	if [ "$1" = "$HELP" ]; then
-		pu
-	else
-		# run roscore with the manually specified uri  
-		./$NAME $1
-	fi
-else
-	pu
+#################################################### Check ROS_MASTER_URI
+if [ -z "$ROS_MASTER_URI" ]; then
+    echo "[Jroscore]: ROS_MASTER_URI not found -> ROS probably not installed. Setting the default URI."
+    ROS_MASTER_URI=$DEFAULTURI
 fi
+
+#################################################### Launch the Java RosCore
+if [ "$URI" != "1" ]; then
+    # some argment without -u prefix?
+    if [ "$#" -ne "0" ]; then 
+        usage
+    fi
+    # Launch java core, remember its PID and continue this script
+    java -cp "build/install/jroscore/lib/*" ctu.nengoros.Jroscore $DEFAULTURI &
+    PID1="$!"
+    
+else
+    # Launch java core, remember its PID and continue this script
+    java -cp "build/install/jroscore/lib/*" ctu.nengoros.Jroscore $1 &
+    PID1="$!"
+fi
+
+#################################################### Handle the SIGTERM
+cleanup(){
+    echo " Sending SIGTERM further.."
+    kill -s TERM $PID1
+}
+
+# set the trap for SIGTERM signal (CTRL+C)
+trap "cleanup" 15 2 18
+
+# wait for java to finish
+wait
 
 
